---
galaxy_info:
  author: Showroom Project Team
  description: This role prepares the external DB host for AAP installation.
  company: Red Hat, Inc.
  license: GPL-3.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags: []
dependencies: []
collections:
  - community.postgresql
