collection_requirements_list:
  - name: community.hashi_vault
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/community-hashi_vault-6.2.0.tar.gz
    type: url
  - name: infra.aap_utilities
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/infra-aap_utilities-2.8.0.tar.gz
    type: url
  - name: ansible.posix
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/ansible-posix-2.1.0.tar.gz
    type: url
  - name: kubernetes.core
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/kubernetes-core-6.2.0.tar.gz
    type: url
  - name: ansible.utils
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/ansible-utils-6.0.0.tar.gz
    type: url
  - name: community.postgresql
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/community-postgresql-4.1.0.tar.gz 
    type: url
  - name: community.general
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/community-general-12.0.0.tar.gz
    type: url
  - name: infra.aap_configuration
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/infra-aap_configuration-3.8.3.tar.gz
    type: url
  - name: infra.aap_configuration_extended
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/infra-aap_configuration_extended-3.0.2.tar.gz
    type: url
  - name: infra.ee_utilities
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/infra-ee_utilities-4.2.0.tar.gz
    type: url
  - name: ansible.platform
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/ansible-platform-2.6.20250924.tar.gz
    type: url
  - name: ansible.controller
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/ansible-controller-4.7.4.tar.gz
    type: url
  - name: containers.podman
    source: https://pforgeipt.example.com/nexus3/repository/sim-assets-public/ansible/galaxy/containers-podman-1.16.4.tar.gz
    type: url

role_requirements_list:
  - name: RedHatOfficial.rhel9-cis
    version: 0.1.72

