---
galaxy_info:
  author: Showroom Project Team
  description: This role downloads the AAP license file from Red Hat
  company: Red Hat, Inc.
  license: GPL-3.0-only
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags: []
dependencies: []
