---
controller_instance_groups:
  - name: "default"
    policy_instance_minimum: "0"
    policy_instance_percentage: "0"

  - name: "controlplane"
    policy_instance_minimum: "0"
    policy_instance_percentage: "0"
    instances: "{{ groups.automationcontroller }}"

  - name: "executionplane"
    policy_instance_minimum: "0"
    policy_instance_percentage: "100"
    instances: "{{ groups.execution_nodes }}"
