---
controller_settings:
  settings:
    ACTIVITY_STREAM_ENABLED: "true"
    ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC: "false"
    ORG_ADMINS_CAN_SEE_ALL_USERS: "true"
    REMOTE_HOST_HEADERS:
      - HTTP_X_FORWARDED_FOR
      - REMOTE_ADDR
      - REMOTE_HOST
    ALLOW_JINJA_IN_EXTRA_VARS: "template"
    AWX_ISOLATION_BASE_PATH: "/home/aap/aap/controller/data/job_execution"
    INSIGHTS_TRACKING_STATE: false
    AWX_ROLES_ENABLED: true
    AWX_COLLECTIONS_ENABLED: true
    MAX_FORKS: "200"
    SCHEDULE_MAX_JOBS: "10"
    LOG_AGGREGATOR_HOST: "syslog.example.com"
    LOG_AGGREGATOR_PORT: 514
    LOG_AGGREGATOR_TYPE: "other"
    LOG_AGGREGATOR_USERNAME: ""
    LOG_AGGREGATOR_PASSWORD: ""
    LOG_AGGREGATOR_LOGGERS:
      - awx
      - activity_stream
      - job_events
      - system_tracking
      - broadcast_websocket
      - job_lifecycle
    LOG_AGGREGATOR_INDIVIDUAL_FACTS: false
    LOG_AGGREGATOR_ENABLED: true
    LOG_AGGREGATOR_TOWER_UUID: "aap-staging"
    LOG_AGGREGATOR_PROTOCOL: "udp"
    LOG_AGGREGATOR_TCP_TIMEOUT: 5
    LOG_AGGREGATOR_VERIFY_CERT: true
    LOG_AGGREGATOR_LEVEL: "INFO"
    LOG_AGGREGATOR_ACTION_QUEUE_SIZE: 131072
    LOG_AGGREGATOR_ACTION_MAX_DISK_USAGE_GB: 5
    LOG_AGGREGATOR_MAX_DISK_USAGE_PATH: "/var/lib/awx"
    LOG_AGGREGATOR_RSYSLOGD_DEBUG: false
    API_400_ERROR_LOG_FORMAT: "status {status_code} received by user {user_name} attempting to access {url_path} from {remote_addr}"
    DEFAULT_CONTAINER_RUN_OPTIONS:
      - --network
      - slirp4netns:enable_ipv6=true
      - --security-opt
      - label=level:s0:c100,c200
    RECEPTOR_RELEASE_WORK: "true"
    RECEPTOR_KEEP_WORK_ON_ERROR: "false"
    MAX_UI_JOB_EVENTS: "4000"
    UI_LIVE_UPDATES_ENABLED: "true"
