---
controller_credential_input_sources:
  - target_credential: "Vault Credential"
    source_credential: "Vault Lookup Credential"
    input_field_name: vault_password
    description:
    metadata:
      secret_key: aap_install_vault_token_secret
      secret_path: infraops/data/aap/staging

  - target_credential: "Source Control Credential"
    source_credential: "Vault Lookup Credential"
    input_field_name: password
    description:
    metadata:
      secret_key: password
      secret_path: devops/data/pforgeipt-divisional/sim/sim-build-readonly

  - target_credential: "Source Control Credential"
    source_credential: "Vault Lookup Credential"
    input_field_name: username
    description:
    metadata:
      secret_key: username
      secret_path: devops/data/pforgeipt-divisional/sim/sim-build-readonly

  - target_credential: "Netbox Credential"
    source_credential: "Vault Lookup Credential"
    input_field_name: NETBOX_TOKEN
    description:
    metadata:
      secret_key: netbox-api-token
      secret_path: infraops/data/aap/staging

  - target_credential: "Private Automation Hub Registry Credential"
    source_credential: "Vault Lookup Credential"
    input_field_name: password
    description:
    metadata:
      secret_key: hub_admin_password_secret
      secret_path: infraops/data/aap/staging

  - target_credential: "Machine Credential"
    source_credential: "Vault Lookup Credential"
    input_field_name: ssh_key_data
    description:
    metadata:
      secret_key: aap_service_user_ssh_private_key
      secret_path: infraops/data/aap/staging
