---
controller_inventory_sources:
  - name: "Netbox Source Inventory"
    description: "This is the source plugin for Netbox inventory"
    organization: "{{ aap_config_organization }}"
    source: "scm"
    limit: ""
    source_project: "inventory-aap"
    source_path: "netbox-access-switches-staging.yml"
    inventory: "SCM Inventory"
    update_on_launch: "true"
    overwrite: "true"
    overwrite_vars: "true"
    credential: "Netbox Credential"
    execution_environment: "Custom Execution Environment"

  - name: "Source SCM Inventory"
    description: "This the AAP inventory from SCM"
    organization: "{{ aap_config_organization }}"
    source: "scm"
    limit: ""
    source_project: "inventory-aap"
    source_path: "inventory-dev.yml"
    inventory: "SCM Inventory"
    update_on_launch: "true"
    overwrite: "true"
    overwrite_vars: "true"
