---
hub_collections:
  - namespace: "netbox"
    name: "netbox"
    path: "{{ aap_setup_down_dest_dir }}/collections/netbox-netbox-3.21.0.tar.gz"
    repository: rh-certified
    state: present

  - namespace: "community"
    name: "postgresql"
    path: "{{ aap_setup_down_dest_dir }}/collections/community-postgresql-4.1.0.tar.gz"
    repository: community
    state: present

  - namespace: "community"
    name: "general"
    path: "{{ aap_setup_down_dest_dir }}/collections/community-general-12.0.0.tar.gz"
    repository: community
    state: present

  - namespace: "community"
    name: "hashi_vault"
    path: "{{ aap_setup_down_dest_dir }}/collections/community-hashi_vault-6.2.0.tar.gz"
    repository: community
    state: present

  - namespace: "redhat"
    name: "rhel_system_roles"
    path: "{{ aap_setup_down_dest_dir }}/collections/redhat-rhel_system_roles-1.108.6.tar.gz"
    repository: rh-certified
    state: present

  - namespace: "hashicorp"
    name: "vault"
    path: "{{ aap_setup_down_dest_dir }}/collections/hashicorp-vault-1.0.0.tar.gz"
    repository: rh-certified
    state: present

  - namespace: "ansible"
    name: "posix"
    path: "{{ aap_setup_down_dest_dir }}/collections/ansible-posix-2.1.0.tar.gz"
    repository: rh-certified
    state: present

  - namespace: "ansible"
    name: "utils"
    path: "{{ aap_setup_down_dest_dir }}/collections/ansible-utils-6.0.0.tar.gz"
    repository: rh-certified
    state: present

  - namespace: "infra"
    name: "aap_configuration"
    path: "{{ aap_setup_down_dest_dir }}/collections/infra-aap_configuration-3.8.3.tar.gz"
    repository: validated
    state: present

  - namespace: "infra"
    name: "aap_configuration_extended"
    path: "{{ aap_setup_down_dest_dir }}/collections/infra-aap_configuration_extended-3.0.2.tar.gz"
    repository: validated
    state: present

  - namespace: "infra"
    name: "aap_utilities"
    path: "{{ aap_setup_down_dest_dir }}/collections/infra-aap_utilities-2.8.0.tar.gz"
    repository: validated
    state: present

  - namespace: "containers"
    name: "podman"
    path: "{{ aap_setup_down_dest_dir }}/collections/containers-podman-1.16.4.tar.gz"
    repository: community
    state: present

  - namespace: "kubernetes"
    name: "core"
    path: "{{ aap_setup_down_dest_dir }}/collections/kubernetes-core-6.2.0.tar.gz"
    repository: rh-certified
    state: present

  - namespace: "infra"
    name: "ee_utilities"
    path: "{{ aap_setup_down_dest_dir }}/collections/infra-ee_utilities-4.2.0.tar.gz"
    repository: validated
    state: present

  - namespace: "ansible"
    name: "platform"
    path: "{{ aap_setup_down_dest_dir }}/collections/ansible-platform-2.6.20250924.tar.gz"
    repository: rh-certified
    state: present

  - namespace: "ansible"
    name: "controller"
    path: "{{ aap_setup_down_dest_dir }}/collections/ansible-controller-4.7.4.tar.gz"
    repository: rh-certified
    state: present

  - namespace: "ansible"
    name: "hub"
    path: "{{ aap_setup_down_dest_dir }}/collections/ansible-hub-1.0.3.tar.gz"
    repository: rh-certified
    state: present

  - namespace: "ansible"
    name: "eda"
    path: "{{ aap_setup_down_dest_dir }}/collections/ansible-eda-2.10.0.tar.gz"
    repository: rh-certified
    state: present

