---
- name: "Prepare External DB host for the installation"
  hosts: "{{ host | default('localhost') }}"
  gather_facts: true
  become: true

  roles:
    - role: prepare_external_db_host
      tags:
        - prepare_external_db_host
      when:
        - groups.external_database is defined
        - host in groups.external_database
        - not managed_database | bool
