---
# Fill in environment specific names
gateway_cert_name: "certificate"
gateway_key_name: "key"
controller_crt_name: "certificate"
controller_key_name: "key"
hub_crt_name: "certificate"
hub_key_name: "key"
eda_crt_name: "certificate"
eda_key_name: "key"
postgres_crt_name: "certificate"
postgres_key_name: "key"
ca_cert_chain_name: "chain.pem"

aap_certs:
  - name: gateway.crt
    content: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_cert_path + ':' + gateway_cert_name) }}"
  - name: gateway.key
    content: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_cert_path + ':' + gateway_key_name) }}"
  - name: controller.crt
    content: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_cert_path + ':' + controller_crt_name) }}"
  - name: controller.key
    content: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_cert_path + ':' + controller_key_name) }}"
  - name: hub.crt
    content: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_cert_path + ':' + hub_crt_name) }}"
  - name: hub.key
    content: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_cert_path + ':' + hub_key_name) }}"
  - name: eda.crt
    content: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_cert_path + ':' + eda_crt_name) }}"
  - name: eda.key
    content: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_cert_path + ':' + eda_key_name) }}"
  - name: postgre.crt
    content: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_cert_path + ':' + postgres_crt_name) }}"
  - name: postgre.key
    content: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_cert_path + ':' + postgres_key_name) }}"
  - name: ca-chain.crt
    content: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_cacert_path + ':' + ca_cert_chain_name) }}"
