---
gateway_admin_username: "{{ vault_gateway_admin_username }}"
gateway_admin_password: "{{ vault_gateway_admin_password }}"
vault_aap_service_user_ssh_private_key: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_secret_path + ':' + 'aap_service_user_ssh_private_key') }}"
vault_gateway_admin_username: "admin"
vault_gateway_admin_password: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'gateway_admin_password_secret') }}"
vault_gateway_pg_password: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'gateway_pg_password_secret') }}"
vault_controller_admin_password: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'controller_admin_password_secret') }}"
vault_controller_pg_password: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'controller_pg_password_secret') }}"
vault_hub_admin_password: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'hub_admin_password_secret') }}"
vault_hub_pg_password: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'hub_pg_password_secret') }}"
vault_eda_admin_password: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'eda_admin_password_secret') }}"
vault_eda_pg_password: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'eda_pg_password_secret') }}"
vault_postgresql_admin_username: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'postgresql_admin_username_secret') }}"
vault_postgresql_admin_password: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'postgresql_admin_password_secret') }}"
# vault_registry_username: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'registry_username_secret' ) }}"
# vault_registry_password: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'registry_password_secret' ) }}"
vault_aap_setup_down_offline_token: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'aap_setup_down_offline_token_secret') }}"
vault_aap_setup_automation_hub_token: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'aap_setup_automation_hub_token_secret') }}"
vault_aap_install_vault_token: "{{ lookup('hashi_vault', hashi_vault_secret_path + ':' + 'aap_install_vault_token_secret') }}"

vault_ext_registry_username: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_registry_path + ':' + 'username') }}"
vault_ext_registry_password: "{{ lookup('community.hashi_vault.hashi_vault', hashi_vault_registry_path + ':' + 'password') }}"
vault_pah_registry_username: "admin"
vault_pah_registry_password: "{{ vault_gateway_admin_password }}"
