---
- name: Include install_collections.yml
  ansible.builtin.include_tasks: install_collections.yml

- name: Include deploy_python_reqs.yml
  ansible.builtin.include_tasks: deploy_python_reqs.yml

- name: Include deploy_packages.yml
  ansible.builtin.include_tasks: deploy_packages.yml

- name: Include prepare_certs.yml
  ansible.builtin.include_tasks: prepare_cacerts.yml

- name: Include prepare_ssh_private_key.yml
  ansible.builtin.include_tasks: prepare_ssh_private_key.yml

- name: Include apply_fixes.yml
  ansible.builtin.include_tasks: apply_fixes.yml

